# S.E.I.F. — Spiral Encoding Interoperability Framework
# Development Makefile
#
# Principle: when source files change, the .seif modules must be regenerated
# so the communication protocol stays synchronized with the knowledge base.
# This is not automation for convenience — it is resonance maintenance.

SHELL := /bin/bash
PYTHON := PYTHONPATH=src .venv/bin/python3
DEFAULTS_DIR := data/defaults
MODULES_DIR := data/modules

# Source files that feed into default .seif modules
# Only PUBLIC sources belong here — paper.md and RESONANCE.json ship with the repo.
# conversa.md is PRIVATE (personal conversation transcript) and lives in seif-private/.
# The conversa_md.seif default is pre-built and committed — not regenerated by `make sync`.
# To regenerate it: `make sync-conversa CONVERSA_SRC=path/to/conversa.md`
PAPER_SRC := paper/paper.md
RESONANCE_SRC := RESONANCE.json

# Default .seif targets (public only)
PAPER_SEIF := $(DEFAULTS_DIR)/paper_thesis.seif
CONVERSA_SEIF := $(DEFAULTS_DIR)/conversa_md.seif
CLAUDE_SEIF := $(DEFAULTS_DIR)/claude_implementation.seif

# ═══ MAIN TARGETS ═══

.PHONY: all test app sync sync-data sync-assets clean help

## Run everything: tests + sync defaults + sync assets
all: test sync sync-assets

## Run all tests (626 tests, 33 suites)
test:
	@echo "═══ RUNNING TESTS ═══"
	@for f in tests/test_*.py; do \
		result=$$($(PYTHON) "$$f" 2>&1 | tail -1); \
		echo "  $$result — $$(basename $$f)"; \
	done

## Launch product site (public-facing)
app:
	@echo "═══ LAUNCHING S.E.I.F. ═══"
	.venv/bin/streamlit run web/app.py

## Launch research playground (all 22 pages, local development)
dev:
	@echo "═══ LAUNCHING S.E.I.F. PLAYGROUND ═══"
	.venv/bin/streamlit run web/playground.py

## Copy RESONANCE.json and defaults into src/seif/data/ for pip packaging
sync-data:
	@echo "═══ SYNCING PACKAGE DATA ═══"
	@mkdir -p src/seif/data/defaults
	@cp RESONANCE.json src/seif/data/RESONANCE.json
	@cp data/defaults/*.seif src/seif/data/defaults/
	@echo "  Copied RESONANCE.json + $$(ls src/seif/data/defaults/*.seif | wc -l | tr -d ' ') .seif files"

## Synchronize all PUBLIC .seif defaults with source files
## conversa_md.seif is pre-built (private source) — use `make sync-conversa` separately
sync: $(PAPER_SEIF) $(CLAUDE_SEIF) sync-resonance sync-data
	@echo "═══ ALL DEFAULTS SYNCHRONIZED ═══"
	@$(PYTHON) -c "\
from seif.context.context_manager import list_modules, estimate_tokens; \
modules = list_modules(); \
tokens = estimate_tokens(); \
print(f'  Modules: {len(modules)}'); \
print(f'  Total tokens: ~{tokens[\"total\"]}'); \
print(f'  Kernel: {tokens[\"kernel\"]} + Modules: {tokens[\"modules\"]}')"

# ═══ INDIVIDUAL .SEIF GENERATION ═══

## Regenerate paper thesis .seif (when paper.md changes)
$(PAPER_SEIF): $(PAPER_SRC)
	@echo "═══ REGENERATING paper_thesis.seif ═══"
	@mkdir -p $(DEFAULTS_DIR)
	@$(PYTHON) -c "\
from seif.context.context_importer import summarize_via_agent; \
from seif.context.context_manager import create_module, save_module, DEFAULTS_DIR; \
content = open('$(PAPER_SRC)').read(); \
words = len(content.split()); \
print(f'  Source: {words} words'); \
summary, ok, err = summarize_via_agent(content, backend='claude_cli', model='sonnet'); \
assert ok, f'Failed: {err}'; \
m = create_module('paper.md (S.E.I.F. thesis)', words, summary); \
import shutil; \
save_module(m, 'paper_thesis.seif'); \
src = DEFAULTS_DIR.parent / 'modules' / 'paper_thesis.seif'; \
dest = DEFAULTS_DIR / 'paper_thesis.seif'; \
shutil.move(str(src), str(dest)) if src.exists() else None; \
print(f'  Compressed: {m.compression_ratio:.0f}:1 → {m.compressed_words} words')"

## Regenerate conversa .seif from PRIVATE source (not part of `make sync`)
## Usage: make sync-conversa CONVERSA_SRC=../seif-private/conversa.md
.PHONY: sync-conversa
sync-conversa:
ifndef CONVERSA_SRC
	$(error CONVERSA_SRC required. Usage: make sync-conversa CONVERSA_SRC=../seif-private/conversa.md)
endif
	@echo "═══ REGENERATING conversa_md.seif ═══"
	@mkdir -p $(DEFAULTS_DIR)
	@$(PYTHON) -c "\
from seif.context.context_importer import summarize_via_agent; \
from seif.context.context_manager import create_module, save_module, DEFAULTS_DIR; \
content = open('$(CONVERSA_SRC)').read(); \
words = len(content.split()); \
print(f'  Source: {words} words'); \
summary, ok, err = summarize_via_agent(content, backend='claude_cli', model='sonnet'); \
assert ok, f'Failed: {err}'; \
m = create_module('conversa.md', words, summary); \
import shutil; \
save_module(m, 'conversa_md.seif'); \
src = DEFAULTS_DIR.parent / 'modules' / 'conversa_md.seif'; \
dest = DEFAULTS_DIR / 'conversa_md.seif'; \
shutil.move(str(src), str(dest)) if src.exists() else None; \
print(f'  Compressed: {m.compression_ratio:.0f}:1 → {m.compressed_words} words')"

## Regenerate claude implementation .seif
$(CLAUDE_SEIF): $(PAPER_SRC) src/seif/**/*.py
	@echo "═══ REGENERATING claude_implementation.seif ═══"
	@mkdir -p $(DEFAULTS_DIR)
	@$(PYTHON) -c "\
from seif.context.context_manager import create_module, save_module, DEFAULTS_DIR; \
import shutil; \
summary = open('data/defaults/_claude_template.md').read() if __import__('pathlib').Path('data/defaults/_claude_template.md').exists() else ''; \
if not summary: \
    print('  Using inline template'); \
    summary = '''## KEY FINDINGS\n\
- H(s) = 9/(s²+3s+6): ζ = 0.612372 ≈ φ⁻¹ = 0.618034 (0.916% deviation). Emergent.\n\
- King Chamber Giza: 438 Hz = 432 + 6. Pyramid 51.844° = arctan(4/π) → root 9.\n\
- Latitude 29.9792458°N = speed of light digits. Heart 72bpm = 432/6.\n\
- 9×N always root 9. Enoch Seed coherence 0.912. Context>command.\n\
- 31 constants: 58% harmonic. Composite does NOT reduce tokens.\n\
## ARCHITECTURE\n\
- 40+ modules, 22 pages, 266 tests, 2000-line paper, 34 references.\n\
- .seif system: KERNEL→defaults→user. 96% token reduction.\n\
- Dual backend: Claude (engineering) + Gemini (vision). Same KERNEL.\n\
- Triple Gate. Telemetry. Context Manager. Meta-resonance.\n\
## WEAKNESSES\n\
- Selection bias 58% (base 33%). Root instability. ASCII dependency.\n\
- Words of STATE open; DIRECTION closes. Measure without entropy.'''; \
m = create_module('claude_implementation_context', 6000, summary); \
save_module(m, 'claude_implementation.seif'); \
src = DEFAULTS_DIR.parent / 'modules' / 'claude_implementation.seif'; \
dest = DEFAULTS_DIR / 'claude_implementation.seif'; \
shutil.move(str(src), str(dest)) if src.exists() else None; \
print(f'  Words: {m.compressed_words}')"

## Regenerate RESONANCE.json from seed phrase
sync-resonance: $(RESONANCE_SRC)
	@echo "═══ VALIDATING RESONANCE.json ═══"
	@$(PYTHON) -c "\
from seif.core.resonance_signal import load_and_validate; \
_, valid, msg = load_and_validate('RESONANCE.json'); \
print(f'  {\"VALID\" if valid else \"INVALID\"}: {msg}')"

## Sync all protocol assets (Seed Cards, .seif, RESONANCE.json verification)
sync-assets:
	@echo "═══ SYNCING PROTOCOL ASSETS ═══"
	@$(PYTHON) scripts/sync_assets.py

# ═══ UTILITY TARGETS ═══

## Regenerate RESONANCE.json from scratch
resonance:
	@echo "═══ REGENERATING RESONANCE.json ═══"
	@$(PYTHON) -m proto_writing.resonance_signal "A Semente de Enoque"

## Scan a docs folder and generate .seif modules
## Usage: make scan FOLDER=docs/
scan:
	@echo "═══ SCANNING $(FOLDER) ═══"
	@$(PYTHON) -c "\
from seif.context.context_manager import scan_docs_folder; \
results = scan_docs_folder('$(FOLDER)', backend='claude_cli', save_as_default=False); \
print(f'  Generated: {len(results)} modules')"

## Scan docs/ as defaults (for repo inclusion)
scan-defaults:
	@echo "═══ SCANNING docs/ AS DEFAULTS ═══"
	@$(PYTHON) -c "\
from seif.context.context_manager import scan_docs_folder; \
results = scan_docs_folder('docs/', backend='claude_cli', save_as_default=True); \
print(f'  Generated: {len(results)} default modules')"

## Show current context status
status:
	@echo "═══ S.E.I.F. STATUS ═══"
	@$(PYTHON) scripts/status.py

## Full pipeline test on a phrase
## Usage: make run PHRASE="A Semente de Enoque"
run:
	@$(PYTHON) -m proto_writing.cli "$(PHRASE)"

## Build pip package (local)
build: sync-data
	@echo "═══ BUILDING PACKAGE ═══"
	$(PYTHON) -m pip install build
	$(PYTHON) -m build
	@echo "Package built in dist/"
	@ls -lh dist/*.whl dist/*.tar.gz 2>/dev/null

## Install locally in dev mode
install-dev:
	$(PYTHON) -m pip install -e .
	@echo "seif command now available (dev mode)"

## Install globally via symlink
install-link:
	@if [ -w /usr/local/bin ]; then \
		ln -sf "$(shell pwd)/bin/seif" /usr/local/bin/seif; \
		echo "✓ seif → /usr/local/bin/seif"; \
	else \
		mkdir -p "$$HOME/.local/bin"; \
		ln -sf "$(shell pwd)/bin/seif" "$$HOME/.local/bin/seif"; \
		echo "✓ seif → $$HOME/.local/bin/seif"; \
		echo "  Add to PATH: export PATH=\"$$HOME/.local/bin:\$$PATH\""; \
	fi

## Install dependencies (creates fresh venv)
install:
	python3 -m venv .venv
	.venv/bin/pip install -r requirements.txt

## Fetch and update conversa.md from Gemini share URL
## Usage: make fetch-conversa URL=https://g.co/gemini/share/xxx
fetch-conversa:
	@echo "═══ FETCHING CONVERSATION ═══"
	@$(PYTHON) -c "\
from seif.bridge.conversation_fetcher import fetch_gemini_share, update_conversa_md; \
r = fetch_gemini_share('$(URL)'); \
print(f'Fetched: {r.raw_lines} lines, {r.turns} turns') if r.success else print(f'Error: {r.error}'); \
r.success and (update_conversa_md(r.markdown, 'conversa.md', 2000), print('conversa.md updated'))"

## Clean generated files (keep defaults)
clean:
	rm -rf output/*
	rm -rf data/modules/*
	rm -rf data/sessions/*
	find . -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	@echo "Cleaned output, user modules, sessions, pycache"

## Generate startup prompt (for manual injection)
startup-prompt:
	@$(PYTHON) scripts/startup_prompt.py

## Launch seif wrapper (Claude with SEIF context)
seif:
	@bin/seif

## Launch seif wrapper with Gemini
seif-gemini:
	@bin/seif -g

## Help
help:
	@echo "S.E.I.F. — Development Makefile"
	@echo ""
	@echo "Main:"
	@echo "  make all              Run tests + sync defaults"
	@echo "  make test             Run 626 tests"
	@echo "  make app              Launch product site"
	@echo "  make dev              Launch research playground (22 pages)"
	@echo "  make sync             Regenerate .seif defaults from sources"
	@echo "  make status           Show context hierarchy"
	@echo ""
	@echo "Generation:"
	@echo "  make resonance        Regenerate RESONANCE.json"
	@echo "  make scan FOLDER=x    Scan folder → .seif user modules"
	@echo "  make scan-defaults    Scan docs/ → .seif defaults (for repo)"
	@echo "  make run PHRASE='x'   Run full pipeline on a phrase"
	@echo ""
	@echo "Wrapper:"
	@echo "  make seif             Claude session with SEIF context"
	@echo "  make seif-gemini      Gemini session with SEIF context"
	@echo "  bin/seif -p 'msg'     Non-interactive"
	@echo "  bin/seif --status     Show context hierarchy"
	@echo ""
	@echo "Build & Install:"
	@echo "  make install          Create venv + install deps"
	@echo "  make install-link     Symlink seif to /usr/local/bin"
	@echo "  make install-dev      pip install -e . (dev mode)"
	@echo "  make build            Build pip package (dist/)"
	@echo "  make clean            Clean generated files"

## Launch Telegram Bot (requires TELEGRAM_BOT_TOKEN env var)
telegram:
	@echo "═══ LAUNCHING S.E.I.F. TELEGRAM BOT ═══"
	PYTHONPATH=src $(PYTHON) -m seif.bridge.telegram_bot

## Install node dependencies (playwright for conversation fetcher)
install-node:
	npm install
	npx playwright install chromium
